### ISSUE TITLE
Moodle - Task scheduled

### ISSUE THREAD

**Issue by angober** [mudrd8mz/moodle-mod_subcourse#13]
Hi, when you deleted the plugin in Moodle, it doesn´t delete in database moodle (mdl_task_scheduled) the reference to task scheduled and when executed cron.php I see this notice:

PHP Notice:  Failed to load task: \mod_subcourse\task\fetch_grades* line 268 of /lib/classes/task/manager.php: call to debugging()
* line 475 of /lib/classes/task/manager.php: call to core\task\manager::scheduled_task_from_record()
* line 66 of /lib/cronlib.php: call to core\task\manager::get_next_scheduled_task()
* line 61 of /admin/cli/cron.php: call to cron_run()
 in /aplicaciones/moodle/e-formacio/e-formacio-eva/lib/weblib.php on line 2949

**Comment by mudrd8mz** [comment]
Thanks for the report. How did you delete the module from Moodle?

**Comment by angober** [comment]
Instead of deleting it from the Moodle plugins administration, the code was removed directly from disk and when I accessed a Moodle was eliminated by saying that plugin not exist.

**Comment by angober** [comment]
It was this way because I´m working with SVN and the new code uploaded don´t have the code of the plugin

**Comment by mudrd8mz** [comment]
I am afraid this is not a bug then. You are not supposed to simply delete the plugin files from the disk and expect that Moodle will cope with it somehow. If the plugin was uninstalled properly via the administration interface, all the registered tasks, created database tables and other relics would be correctly removed. Moodle core intentionally keeps these data unless the plugin is uninstalled.

You should be able to fix your issue by putting the module files back, uninstalling the plugin from the admin interface and only then remove the files (if Moodle is not able to do it itself during the uninstallation procedure).

**Comment by angober** [comment]
Ok, thanks for all
