### ISSUE TITLE
Request: Subcourse activity completion based on course completion

### ISSUE THREAD

**Issue by websquared** [mudrd8mz/moodle-mod_subcourse#16]
Right now completion is based on course grade. Is it possible to make it based on course completion instead? There are a lot of cases where child course activities do not have grades or grade book is not setup on a child course.

**Comment by mudrd8mz** [comment]
Are you suggesting you would like to use just the completion without actual grades. So every time a subcourse is completed, the activity would be marked as completed, too (even if there would be no grade synced).

If so, then +1 it looks like a useful feature.

**Comment by websquared** [comment]
Exactly - in our case we don't use grades, just a simple completion based on viewing the activities. But still would like to pass this information to the parent course - to mark subcourse completed!

**Comment by mudrd8mz** [comment]
![image](https://user-images.githubusercontent.com/85831/28191793-cde24590-6832-11e7-9e02-90a3fd4daf29.png)

**Comment by mudrd8mz** [comment]
Implemented in 5.0.0

**Comment by websquared** [comment]
That's great, thanks!
