### ISSUE TITLE
Performance issue during bulk user import

### ISSUE THREAD

**Issue by ak4t0sh** [mudrd8mz/moodle-mod_subcourse#17]
On `\core\event\role_assigned` event the [\mod_subcourse\observers::role_assigned()](https://github.com/mudrd8mz/moodle-mod_subcourse/blob/master/classes/observers.php#L63) method is called.
This method call `subcourse_grades_update()` for each subcourse for the given course. 
By nature this function require a lot of resources as it fetch grades for all users enrolled in the course.

But on a Moodle with a lot of `mod_subcourse` instances it lead to performance issue during a bulk user import, specially if you have a complex `mod_subcourse` usage. (eg: a `mod_subcourse` instance linked to a course containing `mod_subcourse` instances too.)

Ideally on an import we should compute grades for all users only once at the end, but currently i do not see how we could do it.
I think that a workaround could be to move the `\mod_subcourse\observers::role_assigned()` body into an [Adhoc Task](https://docs.moodle.org/dev/Task_API#Adhoc_tasks) and call this task on the event. This way the import is not block as grades are compute in background. To avoid concurrent call we could use `\core\task\adhoc_task::set_blocking()`.

Unless you think this could lead to blocking side effects  i'll try to implement it soon.

**Comment by mudrd8mz** [comment]
Is this the same case / related to issue #14 ?

**Comment by ak4t0sh** [comment]
Indeed this is same case but on an other event. Maybe we could make #14 more generic and close this issue.

**Comment by mudrd8mz** [comment]
Yeah. I believe that changes required for fixing #14 will address this issues as well.

I started to look at it. I like the idea of making use of the adhoc tasks.

**Comment by mudrd8mz** [comment]
I am going to work on more massive changes in the code organisation and internal API of the module. Fixing this should be much easier then.

**Comment by mudrd8mz** [comment]
What was happening here was that because of the issue #14, every user enrolment triggered update of all users' grades. As a result of f8cea641fe5743e66e7d3bb566d3a8a959291096 we will not update all users' grades now any more. When a new user is enrolled into the referenced course, we will fetch only this user's grades.

I believe this will significantly help this issue too. Only when it will be observed that it is still not enough, I would implement the asynchronous update via adhoc tasks.

**Comment by mudrd8mz** [comment]
@ak4t0sh are you able to test the latest master branch version of the module to see if it helps with your use-case?

**Comment by ak4t0sh** [comment]
:+1: such an efficient patch ! Thanks David !

**Test** : ~ 400 users upload enrolled by cohort sync on multiple courses containing mod_subcourse 
**Results :** 
- Before => ~1min50s but this duration increased at each run (1st : ~1min50, 2nd : ~3min30, 3rd : timeout at 5min due to server configuration)
- Now  => ~1min40s constant duration :)

**Comment by mudrd8mz** [comment]
Thanks. Just out of interest, as it still feels a bit too long to me. What is the users upload time when no subcourse is involved? That is, how much time of that 1min40s is actually spent by the subcourse fetching the grades? If it is significant, it would really make sense to make it async.

**Comment by mudrd8mz** [comment]
Fixed in 5.0.0
