### ISSUE TITLE
Subcourse deadline doesn't show up on student's timeline

### ISSUE THREAD

**Issue by snorrip3** [mudrd8mz/moodle-mod_subcourse#18]
When a deadline is set for the sub-course activity completion, it is not showing up on the student's upcoming events list like other activities would..

The student is expected to progress through subcourses at certain dates so this would be fantastic if it can be fixed somehow.. using latest moodle 3.3 or 3.4

**Comment by mudrd8mz** [comment]
Nice idea!

**Comment by mudrd8mz** [comment]
Fixed in v6.0.0. Thanks again for the suggestion!
