### ISSUE TITLE
Subcourse for mobile app

### ISSUE THREAD

**Issue by Shutiri** [mudrd8mz/moodle-mod_subcourse#19]
Hello David,

Is is possible to have Subcourse activity working on the mobile app?
I'd suggest that the activity jump to the subcourse referenced in it.
Right now, we get a dead end message in the app when opening a subcourse.

Regards

**Comment by mudrd8mz** [comment]
Hi. That is a valid feature request. Any help with adding the mobile app support will be appreciated.

**Comment by mudrd8mz** [comment]
![mod_subcourse_mobile_app](https://user-images.githubusercontent.com/85831/92336896-c4306f00-f0a5-11ea-936f-c719bb06ea07.png)

**Comment by mudrd8mz** [comment]
I am happy to announce that the version 9.0.0 comes with the Moodle Mobile App support.
