### ISSUE TITLE
Go to Course Grades Button

### ISSUE THREAD

**Issue by reactor0138** [mudrd8mz/moodle-mod_subcourse#22]
It would seem to make more sense to have not just a link to the course the grades are coming from but rather the grader report/user report itself. Thus allowing for the drilling down of grades to see how the students got their final marks. Could an additional link be added so they can go to course and go to course grades. For students it would redirect them to the user report and for the staff to grader report of that course?

**Comment by mudrd8mz** [comment]
I just played with it and I agree. Additionally, we could display a progress through the referenced course, if that information is available.

**Comment by mudrd8mz** [comment]
Ok, so the view.php now no longer provides a link to the master course gradebook. Instead, it provides a way to see grades in the referenced course.

Student's view:

![image](https://user-images.githubusercontent.com/85831/44164244-c772ef80-a0c5-11e8-8740-0be6974b00f4.png)

Teacher's view:

![image](https://user-images.githubusercontent.com/85831/44164328-0739d700-a0c6-11e8-99cb-d91e246cdf0e.png)

**Comment by mudrd8mz** [comment]
Fixed in v7.0.0

**Comment by reactor0138** [comment]
You are a true legend!. So a present if you click on the subcourse in the course or from the GB and have the "Redirect to the referenced course" then it takes you straight to the course. If not you get the next page that says go to course, fetch grades. Will the new setting enable us to choose either go direct to course or direct to grades in one click from both the GB and if we click on the subcourse on the front of the course? Your screen shot looks like its the page you get if "Redirect to the referenced course" is not chosen. In the settings it would be good to be able to check either and the one that is checked goes there in one click, whist if both are unchecked then both appear on the inbetween page that has the fetch grades link on it. 
I hope that makes sense. thanks for all your hard work on this. This has revolutionised how our learners track their learning over a 5 year period

**Comment by mudrd8mz** [comment]
The screenshots show the page that is displayed when "Redirect to the referenced course" is not checked. The idea of allowing to jump directly to the referenced course's gradebook is interesting - but no, that is not yet possible. I never thought of using the gradebook as the landing page / navigation point for a course. Is that how your students actually work with Moodle?

I am not against such a feature but I can't promise of getting to it anytime soon.

**Comment by reactor0138** [comment]
Yes we use both the front page of the course. But at the moment on their home page they have a MedSchool Progress button and that takes them to the grades page of our "student progress course" with all the subcourses in it. We use the link to grades as we also have "sitewide user report" installed. This gives the students two options. They can see at a glance their module grades for all years and their progress. Then they have the option to look at a single course and go to the user report for that course via the "subcourse" link in GB or in top right they can choose to see all the user reports from all their courses on one page "sitewide user report. We also use the "sitewide" user report and "subcourse" student progress course for monitoring any student at one time and even a whole cohort over 5 years via the "Grader Report" in the "Student progress course" with all the subcourses in. This gives us a fantastic overview. We currently do not have all this info in our MIS and moodle is much better at a granular level to see right down to the individual submissions. So it's very helpful for us to decide on students progression when they are on the borderline in our "student Progress Commity Meetings"
![image](https://user-images.githubusercontent.com/15623776/44174118-9698b780-a0d1-11e8-81f3-aebc60e6b5fe.png)
![image](https://user-images.githubusercontent.com/15623776/44174149-b334ef80-a0d1-11e8-96b7-67453ec7f416.png)

Yes would be a great feature but we are very grateful you included the link on the other page. this is very helpful. Especially for management who are not so good at navigating moodle.

Thanks again. Your activity has really made a huge difference for our institution

Scott

**Comment by reactor0138** [comment]
Hi David

We have just found that if the grades are hidden in the course they still come through on the subcourse. This prematurely releases the grades to the students before they all come in and are finalised. Emailing you since I could not attached screen shots. Ideally the subcourse should follow the settings of the course and have the grades remain unhidden until they are released. Hope you can help us with this one. cheers

https://github.com/mudrd8mz/moodle-mod_subcourse/issues/28

view from course. Final grade hidden

[cid:image001.png@01D449BF.2C0FA130]

View from grades in the progress course which has the subcourse activities

[cid:image002.png@01D449BF.2C0FA130]

Many thanks

Scott Hallman

E-learning Co-ordinator

Extension 81254
03 3641254
Mobile 021 686 912

Monday 9-5
Tuesday 8:30 to 4:30
Wednesday 9-5
Thursday 8:30 to 4:30
Friday 8:30 to 4:30
