### ISSUE TITLE
Go to Course button should have the option to open in a new window

### ISSUE THREAD

**Issue by nsheehan** [mudrd8mz/moodle-mod_subcourse#27]
We've just started testing the plugin and it looks great. Our only issue is when using the Subcourse activity module, when you click on Go to Course it open in the current window making it more difficult for the student to return to the main course. If you can point me at the file that controls the layout of the Subcourse activity page I can add target="_blank", I have not been able to find the correct file.

Thank you

**Comment by mudrd8mz** [comment]
It should be this line https://github.com/mudrd8mz/moodle-mod_subcourse/blob/2ed7fa3c1610119109fc8e2e4a670b01acae475d/view.php#L136 I have not tested but it should be enough if it reads
```
['class' => 'btn btn-secondary', 'target' => '_blank']
```

**Comment by amjohnson46** [comment]
Hi David,
I tried your edit here and it didn't work. This would be a great feature. Do you have any other suggestions?
Thanks

**Comment by mudrd8mz** [comment]
Hi. Weird it does not work for you. I just tried and it does work for me. The said change makes the link having the expected target attribute, and clicking the button opens the referenced course in a new tab (which is the behaviour for new windows I have set in my browser).

**Comment by amjohnson46** [comment]
Hi David,
Could this possibly depend on the theme? I'm using Boost in Moodle 3.5.3.
Using the Webbrowser inspector, I see that links that open in a new window have the property onclick set to "window.open(_URL_); return false;". When I add the code above, the onclick is still set to "". 
I made sure to purge the caches after the edit. Is there anything else I need to purge/reset?
Thanks for your help,
Aaron

**Comment by amjohnson46** [comment]
Hi David,
I think I figured it out. Above you and Niall were talking about the button within the Subcourse page. Sorry I missed that. I always select the "Redirect to the referenced course" option and so was hoping for this behavior on the link that shows on the course page. Can you direct me to the correct line for that link?
Thanks,
Aaron

**Comment by mudrd8mz** [comment]
Ah. I see! Same feature like the URL resource module has then. I'll have to look how it is done there.

**Comment by lrsmith2** [comment]
Hi, David. I have a client who also dearly wants this feature to work with "Redirect to referenced course" option. Thank you for the help!

**Comment by amjohnson46** [comment]
Hi David,
Yes, copying the URL resource settings for "Appearance" would be perfect. More than I need, but a great solution.
Thanks,
Aaron

**Comment by mudrd8mz** [comment]
The master branch now contains this feature implemented. I think I'll be able to release a new version soon.

![image](https://user-images.githubusercontent.com/85831/50076456-0040e380-01e2-11e9-8518-3b489a6a6d30.png)

**Comment by amjohnson46** [comment]
Excellent! Thanks, David. I think this will be a great improvement for a resuource/plugin that I use extensively.

**Comment by lrsmith2** [comment]
Thanks so much, David. I have been able to successfully test it on my local installation to see if that will work for my client. Next step will be to load it on their test site. I will let you know their feedback. Much appreciated!

**Comment by lrsmith2** [comment]
Hi, David. I ran into a validation error on the client's test site (which is a couple of versions behind my 3.4 local where the plugin DID work). Client is running latest 3.2.9 stable due to other plugin dependencies not yet allowing them to go to a higher version. Can you tell me what version is recommended as base absolute for your master branch? I got "[Error] Required Moodle Version [2017051500]" but am having trouble locating which version that build reference goes to in Moodle's archive of releases. I might need to recommend another upgrade and again weigh pros/cons of what they will lose/gain with them, but am checking here first to see how high they would need to go for this to work. Thanks!

**Comment by mudrd8mz** [comment]
@lrsmith2 the latest Subcourse requires Moodle 3.3 or higher. The version build number for Moodle 3.3 is that 2017051500 which is what the module declares as required minimum. You can find these numerical version numbers at https://docs.moodle.org/dev/Releases#Moodle_3.3

Hope this helps.

**Comment by lrsmith2** [comment]
Extremely helpful as always, David. I knew I was probably looking in the wrong place for the version comparisons. At least going from 3.2.9 to 3.3 won't likely be as big a deal as getting them to 3.4, so that is good.

**Comment by amjohnson46** [comment]
Hi David,
any idea on when a new version will be released with this feature? I've tried manually adding it to my site, but have run into problems (probably my fault).
Thanks,
Aaron

**Comment by mudrd8mz** [comment]
I just released a new version 7.2.0 with this new feature.

Sorry, there is no easy (if possible) way for one plugin to control how another plugin works. In theory, if the Completion Progress block does its job right, then it should respect modules' `...subcourse_get_coursemodule_info()` callbacks and obtain things via something similar to `get_array_of_activities()`. Then, it might be doable. But it is a task for the maintainers of the block. Thank you for understading.

**Comment by lrsmith2** [comment]
Got it. Thank you!
