### ISSUE TITLE
Installation instructions.

### ISSUE THREAD

**Issue by luisdev** [mudrd8mz/moodle-mod_subcourse#31]
Please add installation instructions to the README.md file and the https://github.com/mudrd8mz/moodle-mod_subcourse/wiki page.

**Comment by mudrd8mz** [comment]
Thanks for raising this.

In meanwhile, please refer to the standard Moodle docs https://docs.moodle.org/36/en/Installing_plugins#Installing_a_plugin

There is nothing extra needed when installing this plugin.

**Comment by luisdev** [comment]
Yes, I'm familiar with that doc, but for the "Installing manually at the server" method where do you extract the zip archive to? Is it /moodle/mod/ ?

**Comment by mudrd8mz** [comment]
Yes, it is an activity module and as such, it is supposed to be put into the mod folder.
