### ISSUE TITLE
Feature request: allow fetch by course id

### ISSUE THREAD

**Issue by bfriesenvcc** [mudrd8mz/moodle-mod_subcourse#33]
Right now, it can take a while to find the course I want to fetch from. I'm very used to working with course IDs, so it would be awesome if I could just enter that, instead of searching for the course.

**Comment by mudrd8mz** [comment]
Also related to #34

**Comment by mudrd8mz** [comment]
The #34 has been merged and it should make locating the referenced course much easier.
