### ISSUE TITLE
New feature: fetch calendar events from child courses

### ISSUE THREAD

**Issue by Lehnemann** [mudrd8mz/moodle-mod_subcourse#37]
Hi, there! Great software!

I will suggest a feature: The master course could fetch the calendars from each child course too. In this way, the master course will not only have a unified gradebook but it will have a unified calendar from the childs too.

It's a way to made a central hub for a group of correlated courses. It is a good way to deal with university formations (like Engineering, Biology, etc) that contain several courses within...

**Comment by reactor0138** [comment]
We do this already with our med school. The main calendar on their phones and then front page of moodle already combines the view off all the courses they are on. Students only receive calendar appointments from courses they are enrolled on and if they wander to other courses they become guest students and do not see calendar events as they are not in those groups

**Comment by mudrd8mz** [comment]
Thank you for the interesting suggestion. I think we will need a little bit more clarification here. In a course, the calendar events may come from various sources. There are manually created course-level events and also events that various activity module instances create - such as submission deadlines etc.

In theory, we might be able to do it in a way that all manually created course events from the referenced course are exposed as events reported by the subcourse activity. I don't think we would be able to effectively display other modules' events in the referenced course.

Also, this could likely lead to having some events displayed mutliple times for the users on their dashboard which should already display events from all the courses anyway. So I am not fully convinced about the actual benefits of this feature.

Could you please provide some detailed steps to reproduce your use case (i.e. describe precisely where to create what and what yuu expect to happen). Thank you in advance.

**Comment by mudrd8mz** [comment]
Closing as out of functionality scope.
