### ISSUE TITLE
Upgrading your plugins

### ISSUE THREAD

**Issue by dadou42380** [mudrd8mz/moodle-mod_subcourse#43]
Im David the man who want to pay you for upgrading this pluggins.
I want to use this pluging essentielly for teacher. i have create a link to go directly in the note's page 
![image](https://user-images.githubusercontent.com/83447843/116674167-98e7f080-a9a4-11eb-9a91-cf93b8eaf2b7.png)
-On this page i want to drag and drop the column and row for reajust the read-possibilities 
- I want the colums head with the course image.
- I want a link on the note's student in "english quote???? sorry " which drive me "teacher" on this page détail  : 
 
![image](https://user-images.githubusercontent.com/83447843/116674839-6d193a80-a9a5-11eb-9ee4-b3e34f73a5fb.png)

**Comment by mudrd8mz** [comment]
Thank you for the screenshots. They help to understand me the situation better now, as I was a bit confused by the terminology. That "Notes" is normally referred to as to "Grades" or "Gradebook" so it was not clear to me.

I am afraid your feature request is way beyond the scope of this particular plugin. In fact, it will likely need a custom plugin on its own to implement this behaviour. At the moment, I do not have resources for such a development. Let me encourage you to publish your job offer into https://moodle.org/jobs or contact your local Moodle partner https://moodle.com/partners/

Thank you for understanding.
