### ISSUE TITLE
Links appear to be broken in 3.11

### ISSUE THREAD

**Issue by rvialls** [mudrd8mz/moodle-mod_subcourse#44]
This plugin was working fine for me in Moodle 3.10. I've just upgraded to 3.11. Now when I click on a sub course activity (in any role), instead of being taken to the sub course, I get 403 Forbidden Access to this resource on the server is denied!

Has any testing been done yet with this plugin on 3.11?

**Comment by mudrd8mz** [comment]
That's really unexpected as Moodle does not use this 403 itself. Are you able to debug more? Are the URLs still correct etc?

**Comment by rvialls** [comment]
I've just cracked this. I tried installing a clean version of 3.11 in a sandbox and it worked fine. So I went back at checked the links in the main installation. The links were fine but any attempt to open /mod/subcourse/view.php in a browser got me the 403 error.  Turns out all the files in the mod/subcourse directory were set to 666 permissions rather than 644. I've absolutely no idea how that happened as part of the upgrade though - all the other plugins I'm using were fine. Thanks for you help.

**Comment by mudrd8mz** [comment]
OK, great. Good to see you resolved it. I can't explain what happened with your files permissions too though. It could be that Moodle created files with these lax permissions during the upgrade, and you have some other protection present that prevents from serving / processing files with such open write access, maybe?
