### ISSUE TITLE
coursecatlib has been removed from M3.10

### ISSUE THREAD

**Issue by dasistwas** [mudrd8mz/moodle-mod_subcourse#49]
The library is still used in the version declared compatible with Moodle 3.10:

`./subcourse/mod_form.php:                require_once($CFG->libdir.'/coursecatlib.php');`

**Comment by mudrd8mz** [comment]
Thanks David. Technically, the library is not _used_ - that part of code only gets loaded in Moodle versions 3.5 and lower:

https://github.com/mudrd8mz/moodle-mod_subcourse/blob/d1d0c8e0a2d8b8299ab49ab30d657d1074a779b9/mod_form.php#L124-L129

But I agree it can be removed now as 3.9 is required.
