### ISSUE TITLE
Course Description seems to be repeated in Moodle 4.1

### ISSUE THREAD

**Issue by ChrisCYC** [mudrd8mz/moodle-mod_subcourse#63]
When going in the subcourse activity on Moodle 4.1.1 using boost, the description for the subcourse is listed twice. Once above and once below the Name of the subcourse. I have added a link to a screenshot below to show you what I mean :-)

Any help would be appreciated.  

https://1drv.ms/u/s!AjFCbz0UsHbIhPxFYP_aICKkZaNEUQ?e=MuhRS4

**Comment by mudrd8mz** [comment]
What plugin version are you using?

**Comment by ChrisCYC** [comment]
Hi David, many thanks for the quick response. We are on 10.1.0 (2021021401) 
![Screenshot 2023-02-23 091015](https://user-images.githubusercontent.com/73239085/220864359-6f9dec64-9b6f-4621-9c1d-b37586d4995c.png)

**Comment by pearlphilavong** [comment]
I'm getting the same issue

**Comment by djuricc** [comment]
We are experiencing the same issue with Subcourse version 10.1.0 (2021021401). Adding the following line to styles.css fixes the issue.

#page-mod-subcourse-view .activity-description {
    display: none;
}

I currently have that in the Raw CSS field of my theme. Is there any plan to update the plugin?
