### ISSUE TITLE
Moodle 4.1 support?

### ISSUE THREAD

**Issue by jarvil1** [mudrd8mz/moodle-mod_subcourse#66]
Hello,
Will this plugin support Moodle 4.1?

**Comment by mudrd8mz** [comment]
Well, it does as far as I know. I just haven't found time resources to make sure all the unit tests are updated and a new version supported "officially". But according to https://moodle.org/plugins/mod_subcourse/stats the plugin is used at many 4.1 sites.

**Comment by haiksu** [comment]
Hopefully you'll publish the 4.1 at moodle.org/plugins soon, as we use Moodle Packagist for retrieving plugins.
