### ISSUE TITLE
Error Call to undefined function mod_subcourse\output\external_format_string()

### ISSUE THREAD

**Issue by dreambleacher** [mudrd8mz/moodle-mod_subcourse#68]
Hi! After upgrading moodle to 4.2 on a mobile App the Subcourse module (ver 10.1.0) starts to give this Error: Call to undefined function mod_subcourse\output\external_format_string(). 
Seems no problem working in browser yet...

**Comment by mudrd8mz** [comment]
Thanks for raising this!

**Comment by sebamerlo76** [comment]
Hello! I have the same error. Thank you!

**Comment by stiglitzkleiber** [comment]
Hi there, same problem here.
