### ISSUE TITLE
How does this plug-in work?

### ISSUE THREAD

**Issue by pearlphilavong** [mudrd8mz/moodle-mod_subcourse#69]
Full disclosure, I'm not a developer of any kind. I'm just trying to figure out how to build courses and child courses, which I'm hoping the subcourse plugin can help me accomplish. Apologies in advance if I'm not using the right terminology. 

I got our Moodle partner to install the plugin, but I'm stuck on using it. I'm using [this youtube video](https://www.youtube.com/watch?v=cqxmjrBFzIo) as reference on how to actually use the subcourse plugin because I can't find anything in the wiki that can help me. My issue is that one the subcourse activity is made, there's no ability for me to add activities of resources like at course level. There doesn't seem to be any edit function at all (despite being in edit mode), except for adjusting settings.

Can anyone tell me what I'm doing wrong or point me in the direction of some instructions on how to use this plug-in? Or even guidance on whether this plug-in is fit for the purpose of creating child/ subcourses or something else entirely?

Screenshots attached show course level where I'm able to do normal editing/building of the course, then subcourse level where there is no build capability.

**I'm using Moodle version 4.0.8+ with a custom built theme so things look a little different.** 

### At course level:
![Screenshot 2023-06-09 at 12 44 32 PM](https://github.com/mudrd8mz/moodle-mod_subcourse/assets/136034414/a9a3d93e-5035-43d1-bea7-9d250adcbd4f)

### At subcourse level:
![Screenshot 2023-06-09 at 12 44 42 PM](https://github.com/mudrd8mz/moodle-mod_subcourse/assets/136034414/603bc3c9-f6d0-4d11-a970-53d13427a760)

Thanks in advance for your help.

**Comment by chiaravicere** [comment]
The plugin only makes the link between the main course and the subcourse. You have to build the subcourse by entering the real subcourse, not from the "subcourse" module page. (Right?)

**Comment by pearlphilavong** [comment]
mm. Seems this plugin no longer has the functionality that the youtube video shows. I'm less concerned about pulling over grades, and more concerned about creating a sub-course structure.

**Comment by mudrd8mz** [comment]
What YouTube videos do you refer to? What exact functionality do you mean? The Subcourse module has never done more than pulling the final course grade...

**Comment by pearlphilavong** [comment]
The youtube video hyperlinked in the original post of this discussion

**Comment by pearlphilavong** [comment]
I got in touch with Moodle and asked how they structured their moodle academy which features courses nested within certificates, and they said they utilised this subcourse plugin. An idea which was supported by the youtube video linked. Am now very confused since @mudrd8mz themself is saying otherwise.

**Comment by ak4t0sh** [comment]
In the video we can see "/mod/subpage" in the URL. 
This is not subcourse but mod_subpage : https://github.com/moodleou/moodle-mod_subpage

**Comment by mudrd8mz** [comment]
Good catch @ak4t0sh ! That's right - the video is confusing as they are using the name "Sub Course" for their Subpage module installation.

**Comment by danmarsden** [comment]
closing this off - this is a Catalyst client and we can use our internal WRMS system to provide further help if required. (the issues tracker in github is really for reporting issues rather than asking for help on how to use the plugin.)

@pearlphilavong if you're still having issues, please create a new WR and we can provide some further support if required (Catalyst has recently taken over maintenance of this plugin.)

thanks!
