### ISSUE TITLE
"Redirect to the referenced course" not working

### ISSUE THREAD

**Issue by chiaravicere** [mudrd8mz/moodle-mod_subcourse#71]
Hello, I would like to redirect the user directly to the subcourse instead of the subcourse module view.
But at the moment this option does not work despite it is enabled.
Version: 4.1.2

EDIT: with a real student user, it works. May it be an issue that only affects admin users?

Thank you for checking!

**Comment by reylodev** [comment]
Hello. Awesome plugin. Please i have the same problem... When i click the subcourse, this redirects me to mydomain.com/mod/subcourse/view.php?id=179 and not directly to the course in mydomain.com/course/view.php?id=280.

In the mod view i have a button with the name of my course: Go to MyCourse_Name.

How i can go directly to my course when i press the subcourse?

**Comment by reylodev** [comment]
> Hello, I would like to redirect the user directly to the subcourse instead of the subcourse module view. But at the moment this option does not work despite it is enabled. Version: 4.1.2
> 
> EDIT: with a real student user, it works. May it be an issue that only affects admin users?
> 
> Thank you for checking!

Hello... I use, Redirect plugin of Moodle...

**Comment by danmarsden** [comment]
hi there - yes this is expected behaviour - the help string for that setting states:
"If enabled, users will be redirected to the referenced course when attempting to view the subcourse module page. Does not affect users with the permission to fetch grades manually."

thanks!
