### ISSUE TITLE
Error on Subcourse, Error writing to database

### ISSUE THREAD

**Issue by GerardTBR** [mudrd8mz/moodle-mod_subcourse#72]
I have multiple subcourses, example 10. keeping scores of differnet course and writng the m to a certificate. My problem is that I get this "Error writing to database" on the certificate course. I have increase the server's max_allowed_packet size on my.cnf, but I still get this error. I am using  Moodle 3.11.4

Here is the debug report:

Debug info: Out of range value for column 'grademax' at row 1
UPDATE mdl_grade_items SET courseid = ?,categoryid = ?,itemname = ?,itemtype = ?,itemmodule = ?,iteminstance = ?,itemnumber = ?,iteminfo = ?,idnumber = ?,calculation = ?,gradetype = ?,grademax = ?,grademin = ?,scaleid = ?,outcomeid = ?,gradepass = ?,multfactor = ?,plusfactor = ?,aggregationcoef = ?,aggregationcoef2 = ?,sortorder = ?,display = ?,decimals = ?,locked = ?,locktime = ?,needsupdate = ?,weightoverride = ?,timecreated = ?,timemodified = ?,hidden = ? WHERE id=?
-- line 1619 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->update_record_raw()
-- line 253 of /lib/grade/grade_object.php: call to mysqli_native_moodle_database->update_record()
-- line 312 of /lib/grade/grade_item.php: call to grade_object->update()
-- line 1565 of /lib/grade/grade_category.php: call to grade_item->update()
-- line 454 of /lib/grade/grade_category.php: call to grade_category->auto_update_max()
-- line 1182 of /lib/gradelib.php: call to grade_category->pre_regrade_final_grades()
-- line 448 of /lib/gradelib.php: call to grade_regrade_final_grades()
-- line 311 of /mod/subcourse/lib.php: call to grade_get_grades()
-- line 2126 of /lib/modinfolib.php: call to mod_subcourse_cm_info_view()
-- line 2158 of /lib/modinfolib.php: call to cm_info->call_mod_function()
-- line 1440 of /lib/modinfolib.php: call to cm_info->obtain_view_data()
-- line 1235 of /lib/modinfolib.php: call to cm_info->get_after_link()
-- line 916 of /course/renderer.php: call to cm_info->__get()
-- line 836 of /course/renderer.php: call to core_course_renderer->course_section_cm()
-- line 1051 of /course/renderer.php: call to core_course_renderer->course_section_cm_list_item()
-- line 885 of /course/format/renderer.php: call to core_course_renderer->course_section_cm_list()
-- line 57 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()
-- line 278 of /course/view.php: call to require()
[array (
0 => '129',
1 => NULL,
2 => NULL,
3 => 'course',
4 => NULL,
5 => '130',
6 => NULL,
7 => NULL,
8 => NULL,
9 => NULL,
10 => 1,
11 => 101500.0,
12 => 0.0,
13 => NULL,
14 => NULL,
15 => '0.00000',
16 => 1.0,
17 => 0.0,
18 => 0.0,
19 => 0.0,
20 => '1',
21 => '0',
22 => NULL,
23 => '0',
24 => '0',
25 => 1,
26 => '0',
27 => '1687332062',
28 => 1689232863,
29 => '0',
30 => '5111',
)]
Error code: dmlwriteexception

[error.txt](https://github.com/mudrd8mz/moodle-mod_subcourse/files/12036561/error.txt)

Any Help will be really appreciated.

**Comment by mudrd8mz** [comment]
Hi @GerardTBR Have you figured out what was behind this?

**Comment by GerardTBR** [comment]
Yes, The problem was the MaxGrade variable. It was just the amount of data going through the plugin that was creating the error. All i did was cleaning the grades and it worked.

**Comment by mudrd8mz** [comment]
That's weird. Because as I understand the error, it says that `101500.0` was "out of range value for column 'grademax'". But that is unexpected - that column should be numeric(10, 5) which is way too enough to store such value.

**Comment by GerardTBR** [comment]
I have been struggling with this error for quite some time. But at least it is working again. But with the "maxgrade" variable, that was only one of 16 other "maxgrade" variables displaying on the certificate. I think it was just too much for Moodle to handle.
