### ISSUE TITLE
Button on the App not wrapping text correctly

### ISSUE THREAD

**Issue by davefoord** [mudrd8mz/moodle-mod_subcourse#77]
When accessing a subcourse activity via the Moodle App, of the course being linked to, is longish, rather than wrapping the text within the button, it simple truncates the text at both ends which stops it from making sense.

This has been reported to the Moodle App tracker, via this ticket https://tracker.moodle.org/browse/MOBILE-4480 and they suggest that the subcourse plugin needs to be updated so that the class 

ion-text-wrap

is added to the button. Is this something that could be done?

**Comment by danmarsden** [comment]
thanks Dave - sounds like a sensible change to make - pull requests always welcome! :-)

**Comment by davefoord** [comment]
I Dan - unfortunately I am not a coder, so cannot contribute to pull requests. If I could I would, but this is way outside my skill set.

**Comment by danmarsden** [comment]
Thanks @lskinnercatalyst - I've cherry picked that to the 4.1 and 4.2 branches here in github - @davefoord if you update to the version stored in github it might look a bit better - we haven't pushed to the moodle.org plugins db but will do that at a later date.

thanks!
