### ISSUE TITLE
Subcourse completion not able to be set to passing grade

### ISSUE THREAD

**Issue by reactor0138** [mudrd8mz/moodle-mod_subcourse#90]
Hi Dan. Seems ages. (otago Uni)

I know Our team worked with you guys to get an activity to push through as well as the final grade of a course for subcourses. 

I seem to have come across an oversight/bug. I wanted the completion of the subcourse activity in a course to trigger a certificate (I know i could install a couple of plug ins for restriction but these will take time) 

Anyway, I set a passing grade on the activity in the subcourse (not activity in the real course) I set it to be complete on a passing grade too, and also course completion too. I even then set a passing grade on the subcourse activity in the real course via the gradebook item. 

However no matter which of the 3 passing grades (all set) it always comes back not being able to save. It jsut gives the meassge "This activity does not have a valid grade to pass set. It may be set in the Grade section of the activity settings." in red.

It works for just a grade but that does not help. It seems as though the subcourse activity either can't pick up the passing grade from the course, the passing grade from the activity or the passing grade set in the gradebook for the subcourse activity.

Could you possible look at this. Perhaps I'm missing something and it's our moodle?

Also forgot to mention that I even tried checking "Student must complete the referenced course to complete this activity."
and although this saves, on the front page its says "You have to add at least one completion condition". I was hoping this just checked the and the course complete it might work but did not

![subcourse completion error](https://github.com/user-attachments/assets/9e649744-6d38-4cad-8508-6a79f8ed1eff)

**Comment by reactor0138** [comment]
![reference course to complete this activity](https://github.com/user-attachments/assets/2526c534-286e-454c-ac82-04670ac5552a)
![no completion](https://github.com/user-attachments/assets/2299c386-f3c2-4b4c-bab8-fc67ded76780)

**Comment by danmarsden** [comment]
Hi @reactor0138 - Thanks for the report! - those are actually 2 existing known issues:

#65 and #86 cover those 2 issues but it's also partly mentioned in #15 as well

Unfortunately it's not something we have anyone looking into right now but feel free to reach out privately if you would like to fund some improvements (otherwise, pull requests are always welcome too!!)

thanks,

**Comment by reactor0138** [comment]
Thanks Dan for taking a look. Sorry to waste your time. I'll talk to the Medmoodle team to see if they have some funds

**Comment by danmarsden** [comment]
no worries - the screenshots were really helpful and helped me remember what some of the open issues still are with this plugin - hope all is going well!
